### ISSUE TITLE
error finding libpython

### ISSUE THREAD

**Issue by HariHend1973** [polkabana/bsb_ssd1306_i2c#3]
hai i'm trying to compile this against lede 17.04.01 bit it failed

find /home/hari/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/ssd1306_i2c/ipkg-arm_cortex-a7_neon-vfpv4/ssd1306-i2c -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package ssd1306-i2c is missing dependencies for the following libraries:
libpython2.7.so.1.0
Makefile:52: recipe for target '/home/hari/lede/bin/packages/arm_cortex-a7_neon-vfpv4/base/ssd1306-i2c_0.3-1_arm_cortex-a7_neon-vfpv4.ipk' failed
make[3]: *** [/home/hari/lede/bin/packages/arm_cortex-a7_neon-vfpv4/base/ssd1306-i2c_0.3-1_arm_cortex-a7_neon-vfpv4.ipk] Error 1
make[3]: Leaving directory '/home/hari/lede/package/utils/bsb_ssd1306_i2c'
package/Makefile:105: recipe for target 'package/utils/bsb_ssd1306_i2c/compile' failed
make[2]: *** [package/utils/bsb_ssd1306_i2c/compile] Error 2
make[2]: Leaving directory '/home/hari/lede'
package/Makefile:101: recipe for target '/home/hari/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/stamp/.package_compile' failed
make[1]: *** [/home/hari/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/hari/lede'
/home/hari/lede/include/toplevel.mk:198: recipe for target 'world' failed
make: *** [world] Error 2

however,
hari@ubuntu-uefi:~/lede$ find . -name libpython2.7.so.1.0
./build_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/Python-2.7.13/libpython2.7.so.1.0
./build_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/Python-2.7.13/ipkg-arm_cortex-a7_neon-vfpv4/python-base/usr/lib/libpython2.7.so.1.0
./build_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/Python-2.7.13/ipkg-install/usr/lib/libpython2.7.so.1.0
./staging_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/root-brcm2708/usr/lib/libpython2.7.so.1.0
./staging_dir/target-arm_cortex-a7+neon-vfpv4_musl-1.1.16_eabi/usr/lib/libpython2.7.so.1.0

what's wrong with my build, can you give a clues 

thanks

**Comment by asmfreak** [comment]
I'm no owner, but I think you are building this package with wrong target and toolchain. And/or you should try adding libpython to DEPENDS variable in Makefile and re-run the build

**Comment by HariHend1973** [comment]
Actually i'm using the right toolchain and target, using this source i can compile it properlly. It work like a charm 😊

https://github.com/nmaas87/bsb_ssd1306_i2c.git
